#!/bin/sh
# postinstall script - misopog

init() {
    clear

    echo -ne "
---------------------------------------------------------------------------
            postinstall - a simple post-install script for arch            
---------------------------------------------------------------------------
    "

    # create a few folders (i promise you will need them)
    mkdir -p $HOME/.cache/postinstall/
    mkdir -p $HOME/.local/bin $HOME/.local/src

    sleep 5
    clear
}

yay() {

    # install yay
        git clone https://aur.archlinux.org/yay-bin $HOME/.cache/postinstall/yay-bin
        cd $HOME/.cache/postinstall/yay-bin    
        makepkg -si
    # check if yay is installed and bail if it isn't
        if ! command -v "yay" &> /dev/null; then
            echo "yay is not installed"
            exit 1
        fi
    clear
}



packages() {
    # package list url (the file packages in the repo)
        curl https://raw.githubusercontent.com/misopog/postinstall/main/packages > $HOME/.cache/postinstall/packages
    # i don't know what half of this does i just followed guides on the internet 
        packages=()
        while IFS= read -r line; do
    # ignore lines starting with a #
        if [[ $line == \#* ]]; then
            continue
        fi
    
        package=$(echo "$line" | awk '{print $1}')
        packages+=("$package")
        done < $HOME/.cache/postinstall/packages

    yay -Syu --noconfirm "${packages[@]}"

done < /tmp/packages
    clear
}

setupdots() {

    # if git is not installed, (which it should since it is in the packages file and if it isn't by then i honestly don't know)

    if ! command -v "git" &> /dev/null; then
        echo "git is not installed"
        exit 1
    else
        git clone https://github.com/misopog/dots $HOME/.cache/postinstall/dots
    fi

    # setup the dots (best dotfile init system)
    cd $HOME/.cache/postinstall/dots
    cp * $HOME/

    # user dirs
    mkdir -p $HOME/dl $HOME/dox $HOME/mus $HOME/pix $HOME/vid
    xdg-user-dirs-update

    # enable tap to click
        [ ! -f /etc/X11/xorg.conf.d/40-libinput.conf ] && printf 'Section "InputClass"
                Identifier "libinput touchpad catchall"
                MatchIsTouchpad "on"
                MatchDevicePath "/dev/input/event*"
                Driver "libinput"
	            # Enable left mouse button by tapping
	            Option "Tapping" "on"
        EndSection' >/etc/X11/xorg.conf.d/40-libinput.conf

    # zsh
    chsh -s /bin/zsh

    clear

}

pipewire() {
    # setup pipewire
    systemctl --user enable --now pipewire.socket
    systemctl --user enable --now pipewire-pulse.socket
    systemctl --user enable --now wireplumber.service

    clear
}

sucklesstools() {
    if ! command -v "git" &> /dev/null; then
        echo "git is not installed"
        exit 1
    else
        git clone https://github.com/LukeSmithXYZ/st $HOME/.cache/postinstall/st
        git clone https://github.com/LukeSmithXYZ/dmenu $HOME/.cache/postinstall/dmenu
        cd $HOME/.cache/postinstall/st
        sed -i 's/static int borderpx = 2;/static int borderpx = 20;/' config.h
        sudo make clean install
        cd $HOME/.cache/postinstall/dmenu
        sed -i 's/bh = drw->fonts->h + 2;/bh = drw->fonts->h + 12;/'
        sudo make clean install
        cd $HOME
        clear
    fi

}


init
yay
packages
setupdots
pipewire
sucklesstools
