#!/bin/sh
# postinstall script - misopog

init() {
    clear

    echo -ne "
---------------------------------------------------------------------------
            postinstall - a simple post-install script for arch            
---------------------------------------------------------------------------
             "
    
    sleep 5

    mkdir -p "$HOME/.cache/postinstall/"
    mkdir -p "$HOME/.local/bin" "$HOME/.local/src"
    
# skidded from luke smith

    sudo grep -q "ILoveCandy" /etc/pacman.conf || sudo sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
    sudo sed -Ei "s/^#(ParallelDownloads).*/\1 = 5/;/^#Color$/s/#//" /etc/pacman.conf

    sudo sed -i "s/-j2/-j$(nproc)/;/^#MAKEFLAGS/s/^#//" /etc/makepkg.conf
   
# install yay 

    sudo pacman -Syu git

    git clone https://aur.archlinux.org/yay-bin "$HOME/.cache/postinstall/yay-bin"
    cd "$HOME/.cache/postinstall/yay-bin" || exit

    makepkg -si
	
   cd $HOME
}

pkg() {
    clear

    curl https://raw.githubusercontent.com/misopog/postinstall/main/packages > "$HOME/.cache/postinstall/packages"

    # i don't know what half of this does i just followed guides on the internet 

    packages=()
    while IFS= read -r line; do    
        if [[ $line == \#* ]]; then
            continue
        fi
    package=$(echo "$line" | awk '{print $1}')
    packages+=("$package")
    done < $HOME/.cache/postinstall/packages   
    yay -Syu --noconfirm "${packages[@]}"
}


dots() {
    clear

    git clone https://github.com/misopog/dots "$HOME/.cache/postinstall/dots"
    cd "$HOME/.cache/postinstall/dots" || exit

    cp * "$HOME/"

    mkdir -p "$HOME/dl" "$HOME/dox" "$HOME/mus" "$HOME/pix" "$HOME/vid"
    xdg-user-dirs-update

}


audio() {
    clear

    systemctl --user enable --now pipewire.socket
    systemctl --user enable --now pipewire-pulse.socket
    systemctl --user enable --now wireplumber.service
}


suckless() {
    clear

# until i find a better way to do this, this is the best i can do

    git clone https://github.com/LukeSmithXYZ/st "$HOME/.local/src/st"
    git clone https://github.com/LukeSmithXYZ/dmenu "$HOME/.local/src/dmenu"

    cd $HOME/.local/src/st
    sed -i 's/static int borderpx = 2;/static int borderpx = 20;/' config.h
    sudo make clean install
    cd $HOME/.local/src/dmenu
    sed -i 's/bh = drw->fonts->h + 2;/bh = drw->fonts->h + 12;/'
    sudo make clean install
    cd $HOME
}

ending () {

	clear
	rm -r $HOME/.cache/postinstall/
	    echo -ne "
---------------------------------------------------------------------------
			postinstall - done            
---------------------------------------------------------------------------

postinstall - reboot your computer
Type 'y' to reboot, 'n' to cancel: 			
		     "

    read -r response

    if [[ $response == "y" ]]; then
        reboot
    elif [[ $response == "n" ]]; then
        echo "reboot cancelled"
    fi
	
}

init
pkg
dots
audio
suckless
ending
