#!/bin/sh
# postinstall script - misopog

init() {
    clear

    echo -ne "
---------------------------------------------------------------------------
            postinstall - a simple post-install script for arch            
---------------------------------------------------------------------------
    "

    # create a few folders (i promise you will need them)
    mkdir -p $HOME/.cache/postinstall/
    mkdir -p $HOME/.local/bin $HOME/.local/src

    clear
}

yayinstall() {

    # install yay
        git clone https://aur.archlinux.org/yay-bin $HOME/.cache/postinstall/yay-bin
        cd $HOME/.cache/postinstall/yay-bin    
        makepkg -si
    clear
}



packages() {
    # package list url (the file packages in the repo)
        curl https://raw.githubusercontent.com/misopog/postinstall/main/packages > $HOME/.cache/postinstall/packages
    # i don't know what half of this does i just followed guides on the internet 
        packages=()
        while IFS= read -r line; do
    # ignore lines starting with a #
        if [[ $line == \#* ]]; then
            continue
        fi
    
        package=$(echo "$line" | awk '{print $1}')
        packages+=("$package")
        done < $HOME/.cache/postinstall/packages

    yay -Syu --noconfirm "${packages[@]}"
    clear
}

setupdots() {

    # if git is not installed, (which it should since it is in the packages file and if it isn't by then i honestly don't know)

    if ! command -v "git" &> /dev/null; then
        echo "git is not installed"
        exit 1
    else
        git clone https://github.com/misopog/dots $HOME/.cache/postinstall/dots
    fi

    # setup the dots (best dotfile init system)
    cd $HOME/.cache/postinstall/dots
    cp * $HOME/

    # user dirs
    mkdir -p $HOME/dl $HOME/dox $HOME/mus $HOME/pix $HOME/vid
    xdg-user-dirs-update


sudo bash -c '
    # make pacman colorful, concurrent downloads and pacman eye-candy.
        sudo grep -q "ILoveCandy" /etc/pacman.conf || sudo sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
        sudo sed -Ei "s/^#(ParallelDownloads).*/\1 = 5/;/^#Color$/s/#//" /etc/pacman.conf

    # use all cores for compilation.
        sudo sed -i "s/-j2/-j$(nproc)/;/^#MAKEFLAGS/s/^#//" /etc/makepkg.conf
    '
    clear

}

pipewire() {
    # setup pipewire
    systemctl --user enable --now pipewire.socket
    systemctl --user enable --now pipewire-pulse.socket
    systemctl --user enable --now wireplumber.service

    clear
}

sucklesstools() {
    if ! command -v "git" &> /dev/null; then
        echo "git is not installed"
        exit 1
    else
        git clone https://github.com/LukeSmithXYZ/st $HOME/.cache/postinstall/st
        git clone https://github.com/LukeSmithXYZ/dmenu $HOME/.cache/postinstall/dmenu
        cd $HOME/.cache/postinstall/st
        sed -i 's/static int borderpx = 2;/static int borderpx = 20;/' config.h
        sudo make clean install
        cd $HOME/.cache/postinstall/dmenu
        sed -i 's/bh = drw->fonts->h + 2;/bh = drw->fonts->h + 12;/'
        sudo make clean install
        cd $HOME
        clear
    fi

}

ending() {
    echo -ne "
---------------------------------------------------------------------------
            postinstall - a simple post-install script for arch            
---------------------------------------------------------------------------
             "
    sleep 2
    echo -ne "
---------------------------------------------------------------------------
                                    done                                              
---------------------------------------------------------------------------
             "
    sleep 2
    echo -ne "
---------------------------------------------------------------------------
                            rebooting in 10 seconds                                                                  
---------------------------------------------------------------------------
             "
    sleep 10
    reboot
}

init
yayinstall
packages
setupdots
pipewire
sucklesstools